In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path=r"E:\bishe\LSTM\output.csv"
dataset=pd.read_csv(file_path)

In [ ]:
dataset = dataset[["time_s","Ecell_V","I_mA","Temperature__C","cycleNumber","Ns","SOC"]]
# [0,50,101,152,203,254,305,356,407,458,509,560,611,662,713,764,815,846]
delete_list = [0,51,102,153,204,255,306,357,408,459,510,561,612,663,713,765]

dataset = dataset[ ~dataset["cycleNumber"].isin(delete_list) ]

In [4]:
dataset

,time_s,Ecell_V,I_mA,Temperature__C,cycleNumber,Ns,SOC
19211,2.710614e+04,3.189916,2991.6648,21.487158,1,0,-1.249001e-15
19212,2.713614e+04,3.294316,2991.6650,22.056469,1,0,8.068588e-03
19213,2.716614e+04,3.363116,2992.2561,22.364847,1,0,1.613714e-02
19214,2.719614e+04,3.414705,2989.4978,22.926250,1,0,2.420486e-02
19215,2.722614e+04,3.455032,2991.0737,23.456028,1,0,3.227228e-02
...,...,...,...,...,...,...,...
1075683,6.346237e+06,3.638864,0.0000,22.380661,845,8,1.964810e-01
1075684,6.346267e+06,3.638943,0.0000,22.436010,845,8,1.964810e-01
1075685,6.346297e+06,3.638786,0.0000,22.301590,845,8,1.964810e-01
1075686,6.346327e+06,3.638904,0.0000,22.412289,845,8,1.964810e-01
1075687,6.346339e+06,3.638864,0.0000,22.206705,845,8,1.964810e-01

In [5]:
new_dataset = dataset.values
new_dataset[:,0] = np.round(new_dataset[:,0],2)
new_dataset

array([[ 2.71061400e+04,  3.18991610e+00,  2.99166480e+03, ...,
         1.00000000e+00,  0.00000000e+00, -1.24900090e-15],
       [ 2.71361400e+04,  3.29431630e+00,  2.99166500e+03, ...,
         1.00000000e+00,  0.00000000e+00,  8.06858816e-03],
       [ 2.71661400e+04,  3.36311550e+00,  2.99225610e+03, ...,
         1.00000000e+00,  0.00000000e+00,  1.61371372e-02],
       ...,
       [ 6.34629715e+06,  3.63878560e+00,  0.00000000e+00, ...,
         8.45000000e+02,  8.00000000e+00,  1.96480962e-01],
       [ 6.34632715e+06,  3.63890360e+00,  0.00000000e+00, ...,
         8.45000000e+02,  8.00000000e+00,  1.96480962e-01],
       [ 6.34633884e+06,  3.63886430e+00,  0.00000000e+00, ...,
         8.45000000e+02,  8.00000000e+00,  1.96480962e-01]],
      shape=(815593, 7))

In [6]:
pd.DataFrame(new_dataset)

                 0         1          2          3      4    5             6
0         27106.14  3.189916  2991.6648  21.487158    1.0  0.0 -1.249001e-15
1         27136.14  3.294316  2991.6650  22.056469    1.0  0.0  8.068588e-03
2         27166.14  3.363116  2992.2561  22.364847    1.0  0.0  1.613714e-02
3         27196.14  3.414705  2989.4978  22.926250    1.0  0.0  2.420486e-02
4         27226.14  3.455032  2991.0737  23.456028    1.0  0.0  3.227228e-02
...            ...       ...        ...        ...    ...  ...           ...
815588  6346237.15  3.638864     0.0000  22.380661  845.0  8.0  1.964810e-01
815589  6346267.15  3.638943     0.0000  22.436010  845.0  8.0  1.964810e-01
815590  6346297.15  3.638786     0.0000  22.301590  845.0  8.0  1.964810e-01
815591  6346327.15  3.638904     0.0000  22.412289  845.0  8.0  1.964810e-01
815592  6346338.84  3.638864     0.0000  22.206705  845.0  8.0  1.964810e-01

[815593 rows x 7 columns]

In [ ]:
def split_trajectory_segments(data, dt_thresh=1.01, min_length=30):
    segments = []
    current_seg = [data[0]]
    for i in range(1, len(data)):
        curr = data[i]
        prev = data[i-1]
        dt = curr[0] - prev[0]

        if dt > dt_thresh:
            segments.append(np.array(current_seg))
            current_seg = [curr]
        else:
            current_seg.append(curr)

    if current_seg:
        segments.append(np.array(current_seg))

    filtered_segments = []
    for seg in segments:
        if len(seg) >= min_length:
            filtered_segments.append(seg)
    
    return filtered_segments

seg_data=split_trajectory_segments(new_dataset)

In [11]:
count = 0
for i in range(len(seg_data)):
    print(seg_data[i].shape)
    count+=len(seg_data)
print(len(seg_data))
print(count)

(1589, 7)
(1591, 7)
(1594, 7)
(1578, 7)
(1577, 7)
(1619, 7)
(1666, 7)
(1682, 7)
(1733, 7)
(1742, 7)
(1712, 7)
(1695, 7)
(1685, 7)
(1659, 7)
(1638, 7)
(1631, 7)
(1616, 7)
(1623, 7)
(1619, 7)
(1615, 7)
(1608, 7)
(1612, 7)
(1619, 7)
(1638, 7)
(1634, 7)
(1640, 7)
(1638, 7)
(1645, 7)
(1635, 7)
(1642, 7)
(1637, 7)
(1641, 7)
(1638, 7)
(1643, 7)
(1309, 7)
(335, 7)
(1637, 7)
(1637, 7)
(1634, 7)
(1626, 7)
(1622, 7)
(1611, 7)
(1612, 7)
(1622, 7)
(1602, 7)
(1598, 7)
(1592, 7)
(1581, 7)
(1580, 7)
(1582, 7)
(1577, 7)
(1598, 7)
(1572, 7)
(1567, 7)
(1566, 7)
(1567, 7)
(1575, 7)
(1585, 7)
(1582, 7)
(1586, 7)
(1565, 7)
(1576, 7)
(1590, 7)
(1599, 7)
(1597, 7)
(1605, 7)
(1605, 7)
(1597, 7)
(1591, 7)
(1595, 7)
(1585, 7)
(1576, 7)
(1581, 7)
(1579, 7)
(1563, 7)
(1589, 7)
(1628, 7)
(1642, 7)
(1672, 7)
(1699, 7)
(1696, 7)
(1674, 7)
(1642, 7)
(1622, 7)
(1609, 7)
(1628, 7)
(586, 7)
(1045, 7)
(1616, 7)
(1602, 7)
(1607, 7)
(1647, 7)
(1662, 7)
(1654, 7)
(1687, 7)
(1754, 7)
(1679, 7)
(1677, 7)
(1685, 7)
(1674, 7)
(1666, 7)
(1668, 7)
(1675, 7)
(1710, 7)
(1721, 7)
(661, 7)
(1081, 7)
(1734, 7)
(1631, 7)
(1616, 7)
(1609, 7)
(1598, 7)
(1613, 7)
(1608, 7)
(1608, 7)
(1615, 7)
(1611, 7)
(1614, 7)
(1621, 7)
(1646, 7)
(1663, 7)
(1674, 7)
(1675, 7)
(1667, 7)
(1658, 7)
(1651, 7)
(1645, 7)
(1637, 7)
(1621, 7)
(1627, 7)
(1624, 7)
(1646, 7)
(1677, 7)
(1704, 7)
(1733, 7)
(1761, 7)
(1770, 7)
(1764, 7)
(1742, 7)
(1728, 7)
(1712, 7)
(1691, 7)
(1689, 7)
(1693, 7)
(1808, 7)
(1857, 7)
(1798, 7)
(1804, 7)
(1804, 7)
(1781, 7)
(1784, 7)
(1758, 7)
(1761, 7)
(1687, 7)
(1707, 7)
(1702, 7)
(1712, 7)
(1716, 7)
(1703, 7)
(1721, 7)
(1723, 7)
(1711, 7)
(1703, 7)
(1679, 7)
(1679, 7)
(1676, 7)
(1679, 7)
(1666, 7)
(1725, 7)
(1728, 7)
(1732, 7)
(1757, 7)
(1739, 7)
(1737, 7)
(1727, 7)
(1716, 7)
(1710, 7)
(1699, 7)
(1691, 7)
(1688, 7)
(1673, 7)
(1674, 7)
(1677, 7)
(1684, 7)
(1718, 7)
(1721, 7)
(1712, 7)
(1716, 7)
(1722, 7)
(1715, 7)
(1698, 7)
(1685, 7)
(1689, 7)
(1681, 7)
(1670, 7)
(1678, 7)
(1703, 7)
(1731, 7)
(1757, 7)
(1762, 7)
(1782, 7)
(1771, 7)
(1763, 7)
(1664, 7)
(1687, 7)
(1693, 7)
(1718, 7)
(1708, 7)
(1701, 7)
(1690, 7)
(1690, 7)
(1678, 7)
(1670, 7)
(1668, 7)
(1655, 7)
(1652, 7)
(1651, 7)
(1633, 7)
(1640, 7)
(1637, 7)
(1649, 7)
(1671, 7)
(1685, 7)
(1675, 7)
(1660, 7)
(1643, 7)
(1657, 7)
(1655, 7)
(1654, 7)
(1649, 7)
(1655, 7)
(1653, 7)
(1680, 7)
(1695, 7)
(1679, 7)
(1682, 7)
(1688, 7)
(1668, 7)
(1659, 7)
(1659, 7)
(1655, 7)
(1648, 7)
(1669, 7)
(1658, 7)
(1660, 7)
(1679, 7)
(1700, 7)
(1678, 7)
(1697, 7)
(1703, 7)
(1706, 7)
(1685, 7)
(1701, 7)
(1685, 7)
(1715, 7)
(1714, 7)
(1738, 7)
(1729, 7)
(1716, 7)
(1689, 7)
(1678, 7)
(1687, 7)
(1685, 7)
(1688, 7)
(1689, 7)
(1725, 7)
(1760, 7)
(1769, 7)
(1778, 7)
(1765, 7)
(1762, 7)
(1757, 7)
(1730, 7)
(1718, 7)
(1719, 7)
(1715, 7)
(1707, 7)
(1691, 7)
(1706, 7)
(1731, 7)
(1762, 7)
(1832, 7)
(1825, 7)
(1807, 7)
(1790, 7)
(1792, 7)
(1775, 7)
(1767, 7)
(1773, 7)
(1777, 7)
(1774, 7)
(1772, 7)
(1772, 7)
(1783, 7)
(1828, 7)
(1835, 7)
(1818, 7)
(1810, 7)
(1796, 7)
(1791, 7)
(1784, 7)
(1778, 7)
(1766, 7)
(1823, 7)
(1783, 7)
(1802, 7)
(1810, 7)
(1793, 7)
(1798, 7)
(1785, 7)
(1795, 7)
(1792, 7)
(1781, 7)
(1801, 7)
(1818, 7)
(1861, 7)
(1860, 7)
(33, 7)
(1802, 7)
(1847, 7)
(1845, 7)
(1818, 7)
(1817, 7)
(1811, 7)
(1787, 7)
(1795, 7)
(1812, 7)
(1829, 7)
(1888, 7)
(1879, 7)
(1912, 7)
(1895, 7)
(1839, 7)
(1818, 7)
(1808, 7)
(1819, 7)
(1815, 7)
(1830, 7)
(1814, 7)
(1821, 7)
(1259, 7)
(15328, 7)
(15067, 7)
343
117649

In [9]:
pd.DataFrame(seg_data[15])

              0         1          2          3     4    5         6
0     120389.56  3.936745 -12751.550  21.455530  16.0  4.0  0.956195
1     120390.56  3.797060 -14229.568  21.748093  16.0  4.0  0.954922
2     120391.56  3.779377 -14297.343  21.661114  16.0  4.0  0.953639
3     120392.56  3.766500 -14346.400  21.740185  16.0  4.0  0.952352
4     120393.56  3.755827 -14389.744  21.835070  16.0  4.0  0.951060
...         ...       ...        ...        ...   ...  ...       ...
1626  122013.51  3.678758      0.000  27.275160  16.0  7.0  0.393673
1627  122014.51  3.678758      0.000  27.377951  16.0  7.0  0.393673
1628  122015.51  3.678758      0.000  27.346321  16.0  7.0  0.393673
1629  122016.51  3.678639      0.000  27.132830  16.0  7.0  0.393673
1630  122016.93  3.678679      0.000  27.385857  16.0  7.0  0.393673

[1631 rows x 7 columns]